# -*- coding: utf-8 -*-
"""DLAssignment.ipynb
# Added dataset loading and preprocessing l
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/MohitNaren/DL/blob/main/DLAssignment.ipynb

# Loading Dataset
"""

import kagglehub
path = kagglehub.dataset_download("leoscode/wound-segmentation-images")

import os

print("Dataset Path:", path)
print(os.listdir(path))

for root, dirs, files in os.walk(path):
    print("Root:", root)
    print("Dirs:", dirs)
    print("Files:", len(files))
    break

base_path = path + "/data_wound_seg"

train_img_path = base_path + "/train_images"
train_mask_path = base_path + "/train_masks"

test_img_path = base_path + "/test_images"
test_mask_path = base_path + "/test_masks"

import os
import cv2
import numpy as np
import shutil

dataset_path = "/content/dataset"
train_dir = dataset_path + "/train"
val_dir = dataset_path + "/val"

os.makedirs(train_dir, exist_ok=True)
os.makedirs(val_dir, exist_ok=True)

from sklearn.model_selection import train_test_split

images = os.listdir(train_img_path)

train_imgs, val_imgs = train_test_split(images, test_size=0.2, random_state=42)

def process_and_copy(img_list, target_dir):
    for img_name in img_list:
        img_path = os.path.join(train_img_path, img_name)
        mask_path = os.path.join(train_mask_path, img_name)

        mask = cv2.imread(mask_path, 0)  # grayscale

        # Check if wound exists
        if np.sum(mask) > 0:
            label = "wound"
        else:
            label = "normal"

        os.makedirs(os.path.join(target_dir, label), exist_ok=True)

        shutil.copy(img_path, os.path.join(target_dir, label, img_name))

# Create dataset
process_and_copy(train_imgs, train_dir)
process_and_copy(val_imgs, val_dir)

for cls in os.listdir(train_dir):
    print(cls, ":", len(os.listdir(os.path.join(train_dir, cls))))

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

train_data = datasets.ImageFolder(train_dir, transform=transform)
val_data = datasets.ImageFolder(val_dir, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

print("Classes:", train_data.classes)

import random
import shutil

normal_path = train_dir + "/normal"
normal_images = os.listdir(normal_path)

target_count = 1000  # match closer to wound count

for i in range(target_count - len(normal_images)):
    img = random.choice(normal_images)

    src = os.path.join(normal_path, img)
    dst = os.path.join(normal_path, f"aug_{i}_{img}")

    shutil.copy(src, dst)

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(25),
    transforms.ColorJitter(brightness=0.3, contrast=0.3),
    transforms.RandomAffine(10),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

import torch

# Define device before use
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class_counts = [len(os.listdir(train_dir + "/normal")),
                len(os.listdir(train_dir + "/wound"))]

weights = torch.tensor([
    1.0/class_counts[0],
    1.0/class_counts[1]
])

weights = weights / weights.sum()

criterion = torch.nn.CrossEntropyLoss(weight=weights.to(device))

from torch.utils.data import WeightedRandomSampler

targets = train_data.targets
# Convert targets to a torch.Tensor for element-wise operations
targets_tensor = torch.tensor(targets)

class_sample_count = torch.tensor([
    (targets_tensor == 0).sum(),
    (targets_tensor == 1).sum()
], dtype=torch.float)

weights = 1. / class_sample_count
sample_weights = weights[targets_tensor] # Use targets_tensor here as well

sampler = WeightedRandomSampler(sample_weights, len(sample_weights))

train_loader = DataLoader(train_data, batch_size=32, sampler=sampler)

selected_wounds = random.sample(os.listdir(train_dir + "/wound"), 1000)

for cls in os.listdir(train_dir):
    print(cls, ":", len(os.listdir(os.path.join(train_dir, cls))))

import os
import random

wound_path = train_dir + "/wound"

all_wounds = os.listdir(wound_path)
selected_wounds = random.sample(all_wounds, 1000)

# Remove extra images
for img in all_wounds:
    if img not in selected_wounds:
        os.remove(os.path.join(wound_path, img))

for cls in os.listdir(train_dir):
    print(cls, ":", len(os.listdir(os.path.join(train_dir, cls))))

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

train_data = datasets.ImageFolder(train_dir, transform=transform)
val_data = datasets.ImageFolder(val_dir, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

print(train_data.classes)

"""# Training

### ResNet
"""

import torchvision.models as models
import torch.nn as nn
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.resnet18(pretrained=True)
model.fc = nn.Linear(model.fc.in_features, 2)

model = model.to(device)

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0003)

for epoch in range(10):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print("Validation Accuracy:", 100 * correct / total)

from sklearn.metrics import confusion_matrix
import numpy as np

all_preds = []
all_labels = []

model.eval()

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        outputs = model(images)

        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())

cm = confusion_matrix(all_labels, all_preds)
print(cm)

"""# Week 3"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((64,64)),   # smaller for MLP
    transforms.ToTensor(),
])

train_data = datasets.ImageFolder(train_dir, transform=transform)
val_data = datasets.ImageFolder(val_dir, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64*64*3, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, 2)

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

model = MLP().to(device)

import torch.optim as optim

def train_model(lr):
    model = MLP().to(device)
    optimizer = optim.SGD(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    losses = []

    for epoch in range(5):
        total_loss = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        losses.append(total_loss)
        print(f"LR {lr} Epoch {epoch+1}: Loss {total_loss}")

    return losses

loss1 = train_model(0.1)
loss2 = train_model(0.01)
loss3 = train_model(0.001)

import matplotlib.pyplot as plt

plt.plot(loss1, label="LR=0.1")
plt.plot(loss2, label="LR=0.01")
plt.plot(loss3, label="LR=0.001")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Learning Rate vs Loss")
plt.show()

"""# Week 4

### Optimizations
"""

import torch.optim as optim

def train_with_optimizer(optimizer_name):
    model = MLP().to(device)

    if optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=0.01)
    elif optimizer_name == "Momentum":
        optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
    elif optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=0.001)
    elif optimizer_name == "RMSProp":
        optimizer = optim.RMSprop(model.parameters(), lr=0.001)

    criterion = nn.CrossEntropyLoss()

    losses = []

    for epoch in range(5):
        total_loss = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        losses.append(total_loss)
        print(f"{optimizer_name} Epoch {epoch+1}: Loss {total_loss}")

    return losses

loss_sgd = train_with_optimizer("SGD")
loss_momentum = train_with_optimizer("Momentum")
loss_adam = train_with_optimizer("Adam")
loss_rms = train_with_optimizer("RMSProp")

import matplotlib.pyplot as plt

plt.plot(loss_sgd, label="SGD")
plt.plot(loss_momentum, label="Momentum")
plt.plot(loss_adam, label="Adam")
plt.plot(loss_rms, label="RMSProp")

plt.legend()
plt.title("Optimizer Comparison")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

"""# Week 5"""

import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64*64*3, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, 2)

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x


class MLP_Reg(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64*64*3, 256)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 2)

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

import torch

def train_and_evaluate(model, optimizer, name):
    criterion = nn.CrossEntropyLoss()

    for epoch in range(5):
        model.train()
        train_loss = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # VALIDATION
        model.eval()
        correct = 0
        total = 0

        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)

                _, preds = torch.max(outputs, 1)
                total += labels.size(0)
                correct += (preds == labels).sum().item()

        acc = 100 * correct / total

        print(f"{name} Epoch {epoch+1} | Loss: {train_loss:.2f} | Val Acc: {acc:.2f}%")

import torch.optim as optim

model1 = MLP().to(device)
optimizer1 = optim.SGD(model1.parameters(), lr=0.01)

train_and_evaluate(model1, optimizer1, "No Reg")

model2 = MLP_Reg().to(device)

optimizer2 = optim.SGD(
    model2.parameters(),
    lr=0.01,
    weight_decay=0.001  # L2
)

train_and_evaluate(model2, optimizer2, "With Reg")

"""# Week 6"""

import torch.nn as nn

class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 16 * 16, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv(x)
        x = self.fc(x)
        return x

model = CNN().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

for epoch in range(5):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.2f}")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (preds == labels).sum().item()

print("CNN Accuracy:", 100 * correct / total)

"""# Week 7"""

import torchvision.models as models
import torch.nn as nn

model = models.resnet18(pretrained=True)

# Replace final layer
model.fc = nn.Linear(model.fc.in_features, 2)

model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
criterion = nn.CrossEntropyLoss()

for epoch in range(5):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.2f}")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (preds == labels).sum().item()

print("ResNet Accuracy:", 100 * correct / total)

import torchvision.models as models
import torch.nn as nn

model = models.vgg16(pretrained=True)

# Replace classifier
model.classifier[6] = nn.Linear(model.classifier[6].in_features, 2)

model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
criterion = nn.CrossEntropyLoss()

for epoch in range(5):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.2f}")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (preds == labels).sum().item()

print("VGG Accuracy:", 100 * correct / total)

"""# Week 8"""

import matplotlib.pyplot as plt

# take one batch
images, _ = next(iter(train_loader))
image = images[0].unsqueeze(0).to(device)

model.eval()

# get first conv layer output
with torch.no_grad():
    feature_maps = model.features[0](image)

feature_maps = feature_maps.cpu().squeeze()

# plot first 6 feature maps
for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(feature_maps[i], cmap='gray')
    plt.axis('off')

plt.show()

"""# Week 11"""

class AutoEncoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64*64*3, 256),
            nn.ReLU(),
            nn.Linear(256, 64)
        )

        self.decoder = nn.Sequential(
            nn.Linear(64, 256),
            nn.ReLU(),
            nn.Linear(256, 64*64*3),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x.view(-1, 3, 64, 64)

model = AutoEncoder().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()

for epoch in range(5):
    total_loss = 0

    for images, _ in train_loader:
        images = images.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, images)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

import matplotlib.pyplot as plt

model.eval()
images, _ = next(iter(val_loader))
images = images.to(device)

with torch.no_grad():
    outputs = model(images)

# show original vs reconstructed
for i in range(5):
    plt.subplot(2,5,i+1)
    plt.imshow(images[i].cpu().permute(1,2,0))
    plt.axis('off')

    plt.subplot(2,5,i+6)
    plt.imshow(outputs[i].cpu().permute(1,2,0))
    plt.axis('off')

plt.show()